MVCZoo/Controllers/EspeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCZoo.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace MVCZoo.Controllers
{
    public class EspeciesController : Controller
    {
        private readonly Contexto _context;

        public EspeciesController(Contexto context)
        {
            _context = context;
        }

        // GET: Especies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Especie.ToListAsync());
        }

        // GET: Especies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie
                .Include(Habitat => Habitat.Viven)
                .Include(c => c.Viven)
                .ThenInclude(Viven => Viven.Habitat)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["HabitatId"] = new SelectList(_context.Habitat, "Id", "Nombre");
            if (especie == null)
            {
                return NotFound();
            }

            return View(especie);
        }

        // GET: Especies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Especies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Foto,Nombre_Comun,Nombre_Cientifico,Descripcion")] Especie especie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(especie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(especie);
        }

        // GET: Especies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie.FindAsync(id);
            if (especie == null)
            {
                return NotFound();
            }
            return View(especie);
        }
        public ActionResult AddPhoto(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPhoto(int id, IFormFile Photo)
        {
            if (Photo != null && Photo.Length > 0)
            {

                var fileName = id + ".jpg";

                var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\img", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }

            }
            return RedirectToAction("Details", new { Id = id });
        }

        // POST: Autors/AddHabitat/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddHabitat(int id, [Bind("HabitatId,Indice")] Viven viven)
        {
                viven.EspecieId = id;

            

            try
            {
                _context.Update(viven);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }
            return RedirectToAction("Details", new { Id = id });

        }
        // POST: Especies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Foto,Nombre_Comun,Nombre_Cientifico,Descripcion")] Especie especie)
        {
            if (id != especie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(especie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EspecieExists(especie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(especie);
        }

        // GET: Especies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (especie == null)
            {
                return NotFound();
            }

            return View(especie);
        }

        // POST: Especies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var especie = await _context.Especie.FindAsync(id);
            _context.Especie.Remove(especie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EspecieExists(int id)
        {
            return _context.Especie.Any(e => e.Id == id);
        }
    }
}

MVCZoo/Controllers/HabitatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCZoo.Models;

namespace MVCZoo.Controllers
{
    public class HabitatsController : Controller
    {
        private readonly Contexto _context;

        public HabitatsController(Contexto context)
        {
            _context = context;
        }

        // GET: Habitats
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Habitat.Include(h => h.Itinerario);
            return View(await contexto.ToListAsync());
        }

        // GET: Habitats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat
                .Include(h => h.Itinerario)
                .Include(v => v.Viven)
                .ThenInclude(Viven => Viven.Especie)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["EspecieId"] = new SelectList(_context.Especie, "Id", "Nombre_Comun");
            if (habitat == null)
            {
                return NotFound();
            }

            return View(habitat);
        }

        // GET: Habitats/Create
        public IActionResult Create()
        {
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id");
            return View();
        }

        // POST: Habitats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Clima,Vegetacion,ItinerarioId")] Habitat habitat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(habitat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }
        // POST: Autors/AddEspecie/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEspecie(int id, [Bind("EspecieId")] Viven viven)
        {
            viven.HabitatId = id;



            try
            {
                _context.Update(viven);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {

                throw;

            }
            return RedirectToAction("Details", new { Id = id });

        }
        // GET: Habitats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat.FindAsync(id);
            if (habitat == null)
            {
                return NotFound();
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }

        // POST: Habitats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Clima,Vegetacion,ItinerarioId")] Habitat habitat)
        {
            if (id != habitat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(habitat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HabitatExists(habitat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }

        // GET: Habitats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat
                .Include(h => h.Itinerario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (habitat == null)
            {
                return NotFound();
            }

            return View(habitat);
        }

        // POST: Habitats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var habitat = await _context.Habitat.FindAsync(id);
            _context.Habitat.Remove(habitat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HabitatExists(int id)
        {
            return _context.Habitat.Any(e => e.Id == id);
        }
    }
}

MVCZoo/Views/Especies/AddPhoto.cshtml
@{
    string Pagina = "Añadir foto";
    ViewData["Title"] = Pagina;
}

<h2 class="text-center">@Pagina</h2>
<hr />
    <div>
        <form asp-action="AddPhoto" asp-route-id="@ViewBag.Id" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label class="control-label">Foto:</label>
                <input type="file" name="Photo" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Añadir" class="btn btn-success" />
            </div>
        </form>
    </div>
<div>
    <a class="btn bg-secondary text-white" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCZoo/Views/Especies/Create.cshtml
@model MVCZoo.Models.Especie

@{
    string Pagina = "Crear nueva especie";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina</h1>
<hr />
<div class="row">
    <div class="col-md-4 m-auto">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger">Formato sugerido: nombreanimal.jpg</span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Comun" class="control-label">Nombre común</label>
                <input asp-for="Nombre_Comun" class="form-control" />
                <span asp-validation-for="Nombre_Comun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Cientifico" class="control-label">Nombre científico</label>
                <input asp-for="Nombre_Cientifico" class="form-control" />
                <span asp-validation-for="Nombre_Cientifico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <textarea rows="4" cols="50" asp-for="Descripcion" class="form-control"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn bg-secondary text-white" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCZoo/Views/Especies/Delete.cshtml
@model MVCZoo.Models.Especie

@{
    ViewData["Title"] = "Eliminar especie";
}
<h3>¿Confirma que desea eliminar esta especie?</h3>
<div>
    <h4>Especie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            <img width="200" height="200" src="~/img/@Model.Foto" alt="@Model.Foto" />
        </dd>
        <dt class = "col-sm-2">
            Nombre común
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Comun)
        </dd>
        <dt class = "col-sm-2">
            Nombre científico
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Cientifico)
        </dd>
        <dt class = "col-sm-2">
            Descripción
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Volver a la lista</a>
    </form>
</div>

MVCZoo/Views/Especies/Details.cshtml
@model MVCZoo.Models.Especie

@{
    string Pagina = "Detalles";
    ViewData["Title"] = Pagina; 
}

<h1 class="text-center">@Pagina</h1>

<div>
    <h4>Especie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            <img width="200" height="200" src="~/img/@Model.Foto" alt="@Model.Foto" />
        </dd>
        <dt class="col-sm-2">
            Nombre común
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Comun)
        </dd>
        <dt class="col-sm-2">
            Nombre científico
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre_Cientifico)
        </dd>
        <dt class="col-sm-2">
            Descripción
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
</div>
<h2>Hábitats de @Model.Nombre_Comun:</h2>

@if (Model.Viven.Count == 0)
{
    <p class="text-danger">@Model.Nombre_Comun no tiene ningún hábitat asignado.</p>
}
<ul>
    @foreach (var c in Model.Viven)
    {
        <li class="list-group-item"><a asp-controller="Habitats" asp-action="Details" asp-route-id ="@c.HabitatId">@c.Habitat.Nombre - Índice: @c.Indice</a></li>
    }
</ul> 
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Añadir hábitat
</button>
<div class="collapse" id="collapseExample">

    <form asp-action="AddHabitat" asp-route-id="@Model.Id" method="post">

        <div class="form-group">
            <label class="control-label">Hábitat:</label>
            <select name="HabitatId" class="form-control" asp-items="ViewBag.HabitatId"></select>
        </div>
        <div class="form-group">
            <label class="control-label">Índice:</label>
            <input type="text" name="Indice" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Añadir" class="btn btn-default bg-success text-white" />
        </div>
    </form>
</div>
<hr />
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn-primary btn">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
</div>

MVCZoo/Views/Especies/Edit.cshtml
@model MVCZoo.Models.Especie

@{
    string Pagina = "Editar";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina especie</h1>
<hr />
<div class="row">
    <div class="col-md-4 m-auto">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Comun" class="control-label">Nombre común</label>
                <input asp-for="Nombre_Comun" class="form-control" />
                <span asp-validation-for="Nombre_Comun" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Cientifico" class="control-label">Nombre científico</label>
                <input asp-for="Nombre_Cientifico" class="form-control" />
                <span asp-validation-for="Nombre_Cientifico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripción</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn-primary btn">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCZoo/Views/Especies/Index.cshtml
@model IEnumerable<MVCZoo.Models.Especie>

@{
    string Pagina = "Especies";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina</h1>

<p>
    <a class="btn btn-success shadow" asp-action="Create"><i class="fas fa-plus"></i> <strong>Crear nuevo</strong></a>
</p>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Foto)
            </th>
            <th>
                Nombre común
            </th>
            <th>
                Nombre científico
            </th>
            <th>
                Descripción
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img style="border-radius: 50%;" width="100" height="100" src="~/img/@(item.Id).jpg" alt="@item.Foto" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_Comun)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_Cientifico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" style="width: 44%;" class="btn btn-primary">Editar</a>
                <a asp-action="AddPhoto" asp-route-id="@item.Id" style="width: 44%;" class="btn btn-info">Añadir foto</a>
                <a asp-action="Details" asp-route-id="@item.Id" style="width: 44%;" class="btn btn-secondary">Detalles</a>
                <a asp-action="Delete" asp-route-id="@item.Id" style="width: 44%;" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>