MVCZoo/Models/Habitat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCZoo.Models
{
    public class Habitat
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Clima { get; set; }
        public string Vegetacion { get; set; }
        public int ItinerarioId { get; set; }
        public Itinerario Itinerario { get; set; }
        public ICollection<Viven> Viven { get; set; }
    }
}

MVCZoo/Controllers/EspeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCZoo.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace MVCZoo.Controllers
{
    public class EspeciesController : Controller
    {
        private readonly Contexto _context;

        public EspeciesController(Contexto context)
        {
            _context = context;
        }

        // GET: Especies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Especie.ToListAsync());
        }

        // GET: Especies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie
                .Include(Habitat => Habitat.Viven)
                .Include(c => c.Viven)
                .ThenInclude(Viven => Viven.Habitat)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["HabitatId"] = new SelectList(_context.Habitat, "Id", "Nombre");
            if (especie == null)
            {
                return NotFound();
            }

            return View(especie);
        }

        // GET: Especies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Especies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Foto,Nombre_Comun,Nombre_Cientifico,Descripcion")] Especie especie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(especie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(especie);
        }

        // GET: Especies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie.FindAsync(id);
            if (especie == null)
            {
                return NotFound();
            }
            return View(especie);
        }
        public ActionResult AddPhoto(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPhoto(int id, IFormFile Photo)
        {
            if (Photo != null && Photo.Length > 0)
            {

                var fileName = id + ".jpg";

                var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\img", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }

            }
            return RedirectToAction("Details", new { Id = id });
        }

        // POST: Autors/AddHabitat/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddHabitat(int id, [Bind("HabitatId,Indice")] Viven viven)
        {
                viven.EspecieId = id;

            

            try
            {
                _context.Update(viven);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }
            return RedirectToAction("Details", new { Id = id });

        }
        // POST: Especies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Foto,Nombre_Comun,Nombre_Cientifico,Descripcion")] Especie especie)
        {
            if (id != especie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(especie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EspecieExists(especie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(especie);
        }

        // GET: Especies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var especie = await _context.Especie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (especie == null)
            {
                return NotFound();
            }

            return View(especie);
        }

        // POST: Especies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var especie = await _context.Especie.FindAsync(id);
            _context.Especie.Remove(especie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EspecieExists(int id)
        {
            return _context.Especie.Any(e => e.Id == id);
        }
    }
}

MVCZoo/Controllers/HabitatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCZoo.Models;

namespace MVCZoo.Controllers
{
    public class HabitatsController : Controller
    {
        private readonly Contexto _context;

        public HabitatsController(Contexto context)
        {
            _context = context;
        }

        // GET: Habitats
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Habitat.Include(h => h.Itinerario);
            return View(await contexto.ToListAsync());
        }

        // GET: Habitats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat
                .Include(h => h.Itinerario)
                .Include(v => v.Viven)
                .ThenInclude(Viven => Viven.Especie)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["EspecieId"] = new SelectList(_context.Especie, "Id", "Nombre_Comun");
            if (habitat == null)
            {
                return NotFound();
            }

            return View(habitat);
        }

        // GET: Habitats/Create
        public IActionResult Create()
        {
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id");
            return View();
        }

        // POST: Habitats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Clima,Vegetacion,ItinerarioId")] Habitat habitat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(habitat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }
        // POST: Autors/AddEspecie/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEspecie(int id, [Bind("EspecieId")] Viven viven)
        {
            viven.HabitatId = id;



            try
            {
                _context.Update(viven);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {

                throw;

            }
            return RedirectToAction("Details", new { Id = id });

        }
        // GET: Habitats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat.FindAsync(id);
            if (habitat == null)
            {
                return NotFound();
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }

        // POST: Habitats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Clima,Vegetacion,ItinerarioId")] Habitat habitat)
        {
            if (id != habitat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(habitat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HabitatExists(habitat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItinerarioId"] = new SelectList(_context.Itinerario, "Id", "Id", habitat.ItinerarioId);
            return View(habitat);
        }

        // GET: Habitats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitat = await _context.Habitat
                .Include(h => h.Itinerario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (habitat == null)
            {
                return NotFound();
            }

            return View(habitat);
        }

        // POST: Habitats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var habitat = await _context.Habitat.FindAsync(id);
            _context.Habitat.Remove(habitat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HabitatExists(int id)
        {
            return _context.Habitat.Any(e => e.Id == id);
        }
    }
}

MVCZoo/Views/Habitats/Create.cshtml
@model MVCZoo.Models.Habitat

@{

    string Pagina = "Crear nuevo hábitat";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clima" class="control-label"></label>
                <input asp-for="Clima" class="form-control" />
                <span asp-validation-for="Clima" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vegetacion" class="control-label">Vegetación</label>
                <input asp-for="Vegetacion" class="form-control" />
                <span asp-validation-for="Vegetacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItinerarioId" class="control-label">Itinerario</label>
                <select asp-for="ItinerarioId" class ="form-control" asp-items="ViewBag.ItinerarioId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn bg-secondary text-white" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCZoo/Views/Habitats/Delete.cshtml
@model MVCZoo.Models.Habitat

@{
    ViewData["Title"] = "Eliminar hábitat";
}
<h3>¿Confirma que desea eliminar este hábitat?</h3>
<div>
    <h4>Hábitat</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Clima)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Clima)
        </dd>
        <dt class="col-sm-2">
            Vegetación
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vegetacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Itinerario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Itinerario.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Volver a la lista</a>
    </form>
</div>

MVCZoo/Views/Habitats/Details.cshtml
@model MVCZoo.Models.Habitat

@{
    ViewData["Title"] = "Detalles";
}

<h1 class="text-center">Detalles</h1>

<div>
    <h4>Habitat</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Clima)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Clima)
        </dd>
        <dt class="col-sm-2">
            Vegetación
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vegetacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Itinerario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Itinerario.Codigo)
        </dd>
    </dl>
</div>
<div>
    <h2>Especies de este hábitat:</h2>
    @if (Model.Viven.Count == 0)
    {
        <p class="text-danger">No hay ningún animal asignado a este hábitat.</p>
    }
    <ul class="list-group">
        @foreach (var c in Model.Viven)
        {
            <li class="list-group-item"><a asp-controller="Especies" asp-action="Details" asp-route-id="@c.Especie.Id">@c.Especie.Nombre_Comun</a></li>
        }
    </ul>
</div>
<hr />
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Añadir especie
</button>
<div class="collapse" id="collapseExample">

    <form asp-action="AddEspecie" asp-route-id="@Model.Id" method="post">

        <div class="form-group">
            <label class="control-label">Especie:</label>
            <select name="EspecieId" class="form-control" asp-items="ViewBag.EspecieId"></select>
        </div>
        <div class="form-group">
            <input type="submit" value="Añadir" class="btn btn-default bg-success text-white" />
        </div>
    </form>
</div>
<hr />
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn-primary btn">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
</div>

MVCZoo/Views/Habitats/Edit.cshtml
@model MVCZoo.Models.Habitat

@{
    string Pagina = "Editar";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina</h1>

<h4>Hábitat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clima" class="control-label"></label>
                <input asp-for="Clima" class="form-control" />
                <span asp-validation-for="Clima" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vegetacion" class="control-label">Vegetación</label>
                <input asp-for="Vegetacion" class="form-control" />
                <span asp-validation-for="Vegetacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItinerarioId" class="control-label">Itinerario</label>
                <select asp-for="ItinerarioId" class="form-control" asp-items="ViewBag.ItinerarioId"></select>
                <span asp-validation-for="ItinerarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn-primary btn">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCZoo/Views/Habitats/Index.cshtml
@model IEnumerable<MVCZoo.Models.Habitat>

@{
    string Pagina = "Hábitats";
    ViewData["Title"] = Pagina;
}

<h1 class="text-center">@Pagina</h1>

<p>
    <a class="btn btn-success shadow" asp-action="Create"><i class="fas fa-plus"></i> <strong>Crear nuevo</strong></a>
</p>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clima)
            </th>
            <th>
                Vegetación
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Itinerario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clima)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vegetacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Itinerario.Codigo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>